const mongoose = require("mongoose");

/**
 * AiSlideSchema
 * Defines the structure for individual slides generated by the AI microservice.
 * Stored in a structured format allowing the frontend to render them interactively.
 */
const AiSlideSchema = new mongoose.Schema(
    {
        index: { 
            type: Number, 
            required: true 
        },            
        title: { 
            type: String, 
            required: true, 
            trim: true 
        },
        bullets: { type: [String], default: [] },
        ttsText: { type: String, default: "" },
    },
    { _id: false }
);

/**
 * LessonSchema
 * Represents a single curriculum item, which can be a learning document or a quiz.
 * Handles the logic for rendering original documents vs. AI-generated slides.
 */
const LessonSchema = new mongoose.Schema(
    {
        title: { 
            type: String, 
            required: true, 
            trim: true 
        },
        type: {
            type: String,
            enum: ["lesson", "quiz"], // Defines the lesson format
            required: true,
        },
        durationMin: { type: Number, min: 0, default: null },
        contentUrl: { type: String, default: "" },
        originalDocUrl: { type: String, default: "" },   
        originalDocType: { type: String, default: "" },  // e.g., "pdf", "docx", "pptx", "txt"
        aiSlides: { type: [AiSlideSchema], default: [] },
        useAiSlides: { type: Boolean, default: false },
        useOriginalDoc: { type: Boolean, default: true },
    },
    { _id: false }
);

/**
 * SectionSchema
 * Represents a module or chapter within the course, grouping multiple lessons together.
 */
const SectionSchema = new mongoose.Schema(
    {
        title: { 
            type: String, 
            required: true, 
            trim: true 
        },
        lessons: { type: [LessonSchema], default: [] },
    },
    { _id: false }
);

/**
 * CourseSchema
 * The root database schema for a Course. 
 * Contains all metadata, categorization, access controls, and the nested curriculum (Sections -> Lessons).
 */
const CourseSchema = new mongoose.Schema(
    {
        title: { 
            type: String, 
            required: true, 
            trim: true 
        },
        slug: { 
            type: String, 
            default: "", 
            trim: true 
        },
        subject: {
            type: String,
            enum: ["math", "english", "physics", "chemistry"],
            required: true,
        },
        grade: { 
            type: String, 
            required: true, 
            trim: true 
        },
        learn: { 
            type: [String], 
            default: [] 
        },
        durationText: { 
            type: String, 
            default: "" 
        },
        description: { 
            type: String, 
            default: "" 
        },
        tags: { 
            type: [String], 
            default: [] 
        },
        price: { 
            type: Number, 
            min: 0, 
            default: null 
        },
        visibility: { 
            type: String,
            enum: ["draft", "pending", "published", "rejected", "archived"],
            default: "draft" 
        },
        adminFeedback: { 
            type: String, 
            default: "" 
        },
        coverUrl: { 
            type: String, 
            default: "" 
        },
        sections: { 
            type: [SectionSchema], 
            default: [] 
        },
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },
    },
    { timestamps: true } // Automatically manages `createdAt` and `updatedAt` dates
);

module.exports = mongoose.model("Course", CourseSchema);