const mongoose = require('mongoose');

/**
 * User Schema Definition
 * Represents a user in the BrainBoost platform (Student, Instructor, or Admin).
 * Stores authentication credentials, personal profile data, and learning progress.
 */
const userSchema = new mongoose.Schema({

    // ==== Core Authentication & Identity ====

    fullname: {
        type: String,
        required: true,
        trim: true,
    },
    email: {
        type: String,
        required: true,
        unique: true,   // Ensures no duplicate accounts exist with the same email
        lowercase: true,
    },
    password: {
        type: String,
        required: true, // Stores the bcrypt-hashed password, never plain text
    },

    // ==== Extended Profile Fields ====

    phone: {
        type: String,
        default: '',
    },
    address: {
        type: String,
        default: '',
    },
    avatarUrl: {
        type: String,
        default: '',    // URL to the user's uploaded profile picture
    },
    bannerUrl: {
        type: String,
        default: '',    // URL to the user's uploaded profile background/cover image
    },
    dateOfBirth: {
        type: Date,
        default: null,
    },
    bio: {
        type: String,
        default: '',    // Short biography or description about the user
    },

    // ==== System & Access Control ====

    role: { 
        type: String, 
        enum: ['student','instructor','admin'], 
        default: 'student',
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },

    // ==== Learning & Activity Tracking ====

    // Tracks daily study habits for the dashboard calendar
    study: {
        minutesByDay: { type: Map, of: Number, default: () => {} },
        submittedDays: [String],    // Array of dates (e.g., "YYYY-MM-DD") when tests were submitted
    },

    // List of Test ObjectIds the user has saved/bookmarked for later practice
    bookmarkedTests: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Test',
    }],

    // History of personalized learning paths generated by the AI Advisor
    savedLearningPaths: [{
        goal: String,
        advice: String,
        path: [{
            id: String,
            title: String,
            subject: String,
            grade: String,
            reason: String,
        }],
        savedAt: { type: Date, default: Date.now },
    }],

    // ==== System Settings & Preferences ====

    preferences: {
        isAnonymous: { 
            type: Boolean, 
            default: false,
        },
    },
},

// Schema Options
{ timestamps: true });  // Automatically manages 'createdAt' and 'updatedAt' fields

// Create an explicit index on the email field for faster lookups during login
userSchema.index({ email: 1 }, { unique: true });

module.exports = mongoose.model('User', userSchema);